apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devstaff-mysql
  labels:
    app: devstaff-k8s
spec:
  selector:
    matchLabels:
      app: devstaff-k8s
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devstaff-k8s
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE  # special env var that tells the mysql docker image to create this database
          value: devstaff_db
        - name: MYSQL_USER  # special env var that tells the mysql docker image to create this user
          value: devstaff
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim