apiVersion: v1
kind: Service
metadata:
  name: devstaff-mysql
  labels:
    app: devstaff-k8s
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: devstaff-k8s
    tier: mysql
  clusterIP: None