apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kibana-logging
#  namespace: kube-system
  namespace: logging
  labels:
    k8s-app: kibana-logging
    kubernetes.io/minikube-addons: efk
#    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
#      addonmanager.kubernetes.io/mode: Reconcile
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
#        addonmanager.kubernetes.io/mode: Reconcile
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana-oss:6.3.0
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
#          - name: XPACK_MONITORING_ENABLED
#            value: "false"
#          - name: XPACK_SECURITY_ENABLED
#            value: "false"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP